Updating
updateRoot: aRoot

	aRoot stylesheet
		url:
			('https://use.fontawesome.com/releases/<1s>/css/brands.css' expandMacrosWith: self version);
		anonymousSubResourceIntegrity: 'sha384-IiIL1/ODJBRTrDTFk/pW8j0DUI5/z9m1KYsTm/RjZTNV8RHLGZXkUDwgRRbbQ+Jh'.

	aRoot stylesheet
		url:
			('https://use.fontawesome.com/releases/<1s>/css/fontawesome.css'
				expandMacrosWith: self version);
		anonymousSubResourceIntegrity: 'sha384-q3jl8XQu1OpdLgGFvNRnPdj5VIlCvgsDQTQB6owSOHWlAurxul7f+JpUOVdAiJ5P'.